language: php
php:
  - 5.5
  - 5.4

before_script:
  - composer install

script:
  - vendor/bin/phpcs --standard=phpcs.xml ./src
  - vendor/bin/phpmd src/ text phpmd.xml
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v
